accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views # djangos built in auth
from accounts import views

app_name = 'accounts'

urlpatterns = [
	path('login/', auth_views.LoginView.as_view(template_name= "accounts/login.html"), name='login'), # same as last project
	path('logout/', auth_views.LogoutView.as_view(), name='logout'),
	path('signup/', views.Signup.as_view(), name='signup'),
]

addressbook/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views # djangos built in auth
from addressbook import views

app_name = 'addressbook'

urlpatterns = [
    path('userlist/', views.UserList.as_view(), name='userlist'),
    path('usernumbers/<int:pk>', views.user_phone_numbers, name='usernumbers'),
    path('entry/<int:pk>/', views.PhoneInfoDetail.as_view(), name='phone_entry'),
	
]

phoneaddressbook/urls.py
from django.urls import path, include
from rest_framework.urlpatterns import format_suffix_patterns
from phoneaddressbook.views import PhoneInfoViewSet, UserViewSet, api_root
from rest_framework import renderers
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register(r'phonenumbers', PhoneInfoViewSet)
router.register(r'users', UserViewSet)

urlpatterns = [
	path('', include(router.urls))
]

phonebook/urls.py
from django.contrib import admin
from django.views.generic.base import TemplateView
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('phoneaddressbook.urls')),
	path('accounts/', include('accounts.urls')),
	#path('api-auth/', include('rest_framework.urls')),  # this adds log in/ log out functionality
	path('home/', TemplateView.as_view(template_name='home.html'), name='home'),
	path('addresses/', include('addressbook.urls'))]

accounts/models.py
from django.db import models
from django.contrib import auth # built in django stuff for accounts


class User(auth.models.User,auth.models.PermissionsMixin):
	def __str__(self):
		return self.username # username is an attribute in the auth.models.User class see django docs

# Create your models here.

addressbook/models.py
from django.db import models

# Create your models here.

phoneaddressbook/models.py
from django.db import models

class PhoneInfo(models.Model):
    first_name = models.CharField(max_length=28)
    last_name = models.CharField(max_length=28)
    relationship = models.CharField(max_length=32)
    mobile_number = models.CharField(max_length=12)
    landline_number = models.CharField(max_length=12, blank=True, null=True)
    owner = models.ForeignKey('auth.User', related_name='numbers', on_delete=models.CASCADE)

accounts/forms.py
from django.contrib.auth import get_user_model # this returns the user model currently active in this project
from django.contrib.auth.forms import UserCreationForm

class UserCreateForm(UserCreationForm):
	class Meta():
		fields = ('username','email','password1','password2')
		model = get_user_model()

accounts/views.py
from django.shortcuts import render
from django.views.generic import CreateView
from django.urls import reverse_lazy
from . import forms
# same as last project
class Signup(CreateView):
	form_class = forms.UserCreateForm
	success_url = reverse_lazy('accounts:login')

	template_name = 'accounts/signup.html'

addressbook/views.py
from django.shortcuts import render

from django.views.generic import CreateView, DeleteView, ListView, DetailView, UpdateView

from phoneaddressbook.models import PhoneInfo
from django.http import Http404
from django.contrib.auth import get_user_model
Usera = get_user_model()

from django.contrib.auth.models import User as u

class UserList(ListView):
    
    model = u
    template_name = 'addressbook/user_list.html'
    context_object_name = 'user_list'
	
	
class PhoneInfoDetail(DetailView):
    model = PhoneInfo
    template_name = 'addressbook/phone_info_detail.html'
    context_object_name = 'phoneInfo'

    '''
	Should be all that is needed as just need to display a phone address book entry
	
    '''
    
def user_phone_numbers(request, pk):
        user_name = u.objects.get(pk=pk)
        phone_user = PhoneInfo.objects.filter(owner=user_name)
        
        return render(request, 'addressbook/user_phone_number.html', {'phone_user': phone_user})
        

phoneaddressbook/views.py
from phoneaddressbook.models import PhoneInfo
from phoneaddressbook.serializers import PhoneInfoSerializer, UserSerializer
from phoneaddressbook.permissions import IsOwnerOrReadOnly
from rest_framework import generics, permissions, viewsets
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework.reverse import reverse
from django.contrib.auth.models import User

class PhoneInfoViewSet(viewsets.ModelViewSet):
    queryset = PhoneInfo.objects.all()
    serializer_class = PhoneInfoSerializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly]    

    def perform_create(self, phone_info):
        phone_info.save(owner = self.request.user)

    
class UserViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer

    

@api_view(['GET'])
def api_root(request, format=None):
    return Response({
        'users': reverse('user_list', request=request, format=format),
        'phone_info': reverse('phone_info_list', request=request, format=format)
    })

accounts/templates/accounts/login.html
{% load bootstrap4 %}

{% block content %}
<div class="container">
<form method="POST">
	{% csrf_token %}
	{% bootstrap_form form %}
	<input type="submit" class = 'btn btn-primary' value="Login">
</form>
</div>

{% endblock %}

accounts/templates/accounts/signup.html
{% load bootstrap4 %}

{% block content %}
<div class="container">
<form method="POST">
	{% csrf_token %}
	{% bootstrap_form form %}
	<input type="submit" class = 'btn btn-primary' value="Sign Up">
</form>
</div>
{% endblock %}

addressbook/templates/addressbook/phone_info_detail.html
{{phoneInfo.first_name}}
{{phoneInfo.relationship}}

addressbook/templates/addressbook/user_list.html
<body>

    {% for user in user_list %}
       <a href="{% url 'addressbook:usernumbers' pk=user.id %}"> {{user.username }}</a>
    {% endfor %}
</body>

addressbook/templates/addressbook/user_phone_number.html
<body>

    {% for phone in phone_user %}
        <a href="{% url 'addressbook:phone_entry' pk=phone.id %}">{{phone.first_name }} {{phone.last_name}}</a>
    {% endfor %}
</body>

templates/home.html
<h1><a href="/">Home Page</a></h1>

    {% if user.is_authenticated %} <!-- This is an attribute of djangos model.user --> 
		<a class="nav-item nav-link" href="{% url 'accounts:logout' %}" class="btn btn-simple">Log Out</a>
	{% else %}
	<a class="nav-item nav-link" href="{% url 'accounts:login' %}" class="btn btn-simple">Log In</a>
	<a class="nav-item nav-link" href="{% url 'accounts:signup' %}" class="btn btn-simple">Sign Up</a>
	{% endif %}
	
	<h2><a href="{% url 'addressbook:userlist' %}">List of Users</a></h2>